### ISSUE TITLE
Text/csv file Open Error PySimpleEchem

### ISSUE THREAD

**Issue by abhishekk79** [kevinsmia1939/PySimpleEChem#1]
I tried to select text (.txt) in the drop-down menu of add/open CV in the PySimpleEChem GUI, and the following error appeared in the terminal of VSCode:

Traceback (most recent call last):
  File "c:\Users\abhis\Downloads\Python- Electrochem\PySimpleEChem\PySimpleEChem", line 318, in <lambda>
    cv_txt_action.triggered.connect(lambda: self.cv_open_file('.txt'))
  File "c:\Users\abhis\Downloads\Python- Electrochem\PySimpleEChem\PySimpleEChem", line 336, in cv_open_file
    if self.sender() == self.cv_txt_action:
AttributeError: 'PySimpleEChem_main' object has no attribute 'cv_txt_action'

What might be the issue? Is text file not supported?

Also, I tried to load a CSV file, and another error popped up:

Traceback (most recent call last):
  File "c:\Users\abhis\Downloads\Python- Electrochem\PySimpleEChem\PySimpleEChem", line 316, in <lambda>
    cv_csv_action.triggered.connect(lambda: self.cv_open_file('.csv'))
  File "c:\Users\abhis\Downloads\Python- Electrochem\PySimpleEChem\PySimpleEChem", line 347, in cv_open_file
    self.cv_concat_df,self.cv_param_df, self.cv_2nd_deriv_concat_df = read_cv_format(cv_file,cv_file_format)  
  File "c:\Users\abhis\Downloads\Python- Electrochem\PySimpleEChem\function_collection.py", line 95, in read_cv_format
    cv_df, cv_file_scan_rate = read_cv_corrware(cv_file_path)
  File "c:\Users\abhis\Downloads\Python- Electrochem\PySimpleEChem\function_collection.py", line 62, in read_cv_corrware
    start_segment = search_string_in_file(cv_file_path, 'End Comments')[0][0]
IndexError: list index out of range

What is going on?

**Comment by kevinsmia1939** [comment]
Hi, it is still very much in pre-alpha and most of the stuff is not ready yet. I intended for it to have basic function when I release 1.0.
